export { default as NotFound } from './NotFound';
export { default as SignIn } from './SignIn';
export { default as SignUp } from './SignUp';
export { default as ListPatients } from './ListPatients';
export { default as PatientIdentification } from './PatientIdentification'
export { default as Categories } from './Categories';
export { default as GeneralInfo } from './GeneralInfo';
export { default as PersonalHistory } from './PersonalHistory';
export { default as InitialSymptoms } from './InitialSymptoms';
export { default as Comorbidities } from './Comorbidities';
